### ISSUE TITLE
not window open

### ISSUE THREAD

**Issue by sazearte** [stelic/limitload#5]
Hello, i'have download windows version (limitroad 0.20) et i have this error :
```
[    0.00] INFO: Starting game.
[    0.01] ERROR: Aborting, backtrace follows:
Traceback (most recent call last):
  File "C:\\limload-0.20\\src\main.py", line 1270, in <module>
    main()
  File "C:\\limload-0.20\\src\main.py", line 376, in main
    pandalog=panda_log_real_path)
  File "C:\limload-0.20\src\core\basestack.py", line 136, in __init__
    with_antialiasing, with_bloom)
  File "C:\limload-0.20\src\core\basestack.py", line 349, in _setup_window
    panda_notify.error("Cannot open the window.")
  File "C:\limload-0.20\panda3d\direct\directnotify\Notifier.py", line 131, in error
    raise exception(errorString)
StandardError: Cannot open the window.

```

i'm in windows 10 64bits

**Comment by stelic** [comment]
Heya,

Did you by chance, tweak something in the config.ini? If you did, could you attach it?

Also, what graphic card do you use?

**Comment by sazearte** [comment]
I use a Nvidia 980 et Intel I5 4690 with 16Go of ram
the config file is /config/config.ini.default ?
if yes this is my file :
```
[cpu]
; Number of CPU cores to use: auto, 1, 2, 3.
; Parallel execution may boost performance on multicore CPUs.
use-cores = 2

[video]
; Graphics API: gl, dx8, dx9.
api = gl
; Resolution: desktop, <width> <height>.
resolution = desktop
; Full screen: true, false.
full-screen = true
; Antialiasing: 0, 2, 4
multi-sampling-antialiasing = 4
; Anisotropic filtering: 0, 4, 8, 16
anisotropic-filtering = 16
; Texture pre-loading mode: 0, 1, 2
preload-textures = 2
; Vertical sync: true, false.
vertical-sync = false

[audio]
; Audio system: none, al, fmod.
; It is recommended to use al unless there are errors in sound.
sound-system = al

[misc]
; Language of in-game text: system, <code>
; Language can be set either as default from the user environment (system),
; or requested directly by code, which can be seen from one of available
; language/po/limload/<code>.po files.
language = system
; Frame rate meter: true, false.
frame-rate-meter = false

[path]
; Other game root directories to search.
; Separate multiple paths by colon (:).
; On Linux, automatically included is the root under $XDG_DATA_DIR
; (e.g. $HOME/.local/share/limload).
; %base% can be used to refer to base root directory in the path,
; and %home% to user's home directory.
root-path =

[debug]
; Game debug output level: 0, 1, 2.
output-level = 1
; Panda3D debug output level: fatal, error, warning, info, debug, spam.
panda-output-level = fatal
; Panda3D pstats profiling: true, false.
panda-pstats = false
; Panda3D verbose task timer: true, false.
panda-verbose-timer = false

```

**Comment by stelic** [comment]
After pondering over this, I am not sure where the problem is...

I am also using Windows 10 x64. I never tried game on Intel's graphics so there could be some issues there, but with that other graphic card, it should work just fine.

You could try tweaking config options, like number of cores to use, anti-aliasing, etc. But first, make a copy of "config.ini.default" and name it "config.ini". After that, "config.ini" will be the config file that game will use and the config file that you can tweak.

**Comment by sazearte** [comment]
Yes i found the problem, i change full-screen = true by full-screen = false
Now the game work (in fullscrren), thanks for your help !

**Comment by sazearte** [comment]
i have a question, the campain is not include,  Can we have them, if so how?

**Comment by stelic** [comment]
No campaigns at the moment. Its a bit tricky.

For campaign to work properly, there are few things that need to be improved in the game mechanics first. Particularly AI. And that one keeps being quite tough challenge.

**Comment by sazearte** [comment]
ok thanks
